//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllocationType_t
    {
        public AllocationType_t()
        {
            this.AllocatedTo_t = new HashSet<AllocatedTo_t>();
            this.AssetAllocation_t = new HashSet<AssetAllocation_t>();
        }
    
        public int AllocationTypeID { get; set; }
        public string AllocationTypeName { get; set; }
        public int OUID { get; set; }
    
        public virtual ICollection<AllocatedTo_t> AllocatedTo_t { get; set; }
        public virtual OUs_t OUs_t { get; set; }
        public virtual ICollection<AssetAllocation_t> AssetAllocation_t { get; set; }
    }
}
