//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllocatedTo_t
    {
        public AllocatedTo_t()
        {
            this.AssetAllocation_t = new HashSet<AssetAllocation_t>();
        }
    
        public int AllocatedToID { get; set; }
        public string AllocatedToName { get; set; }
        public int AllocationTypeID { get; set; }
        public string EmpNo { get; set; }
        public Nullable<int> DesignID { get; set; }
        public Nullable<int> DepartID { get; set; }
        public Nullable<int> DivID { get; set; }
        public Nullable<int> StaID { get; set; }
        public Nullable<int> OUID { get; set; }
        public Nullable<int> SOUID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> BPSID { get; set; }
    
        public virtual EmpBPS_t EmpBPS_t { get; set; }
        public virtual EmpDepartments_t EmpDepartments_t { get; set; }
        public virtual EmpDesignations_t EmpDesignations_t { get; set; }
        public virtual EmpDivisions_t EmpDivisions_t { get; set; }
        public virtual SOUs_t SOUs_t { get; set; }
        public virtual EmpStations_t EmpStations_t { get; set; }
        public virtual OUs_t OUs_t { get; set; }
        public virtual AllocationType_t AllocationType_t { get; set; }
        public virtual ICollection<AssetAllocation_t> AssetAllocation_t { get; set; }
    }
}
