//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllocatedTo_v
    {
        public int AllocatedToID { get; set; }
        public string AllocatedToName { get; set; }
        public string EmpNo { get; set; }
        public Nullable<int> OUID { get; set; }
        public Nullable<int> SOUID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string AllocationTypeName { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string Division { get; set; }
        public string StaName { get; set; }
        public Nullable<int> AllocationTypeID { get; set; }
        public Nullable<int> BPS { get; set; }
    }
}
