//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetRetirement_t
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public int CriteriaID { get; set; }
        public int OUID { get; set; }
        public System.DateTime CutOffDate { get; set; }
    
        public virtual AssetRetirementCriteria_t AssetRetirementCriteria_t { get; set; }
        public virtual OUs_t OUs_t { get; set; }
    }
}
