//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetsWithA
    {
        public int AssetID { get; set; }
        public string Category { get; set; }
        public string BCNo { get; set; }
        public string AssetTypeName { get; set; }
        public System.DateTime DoP { get; set; }
        public decimal UnitPrice { get; set; }
        public System.DateTime Auction_Cut_Off_Date { get; set; }
        public Nullable<int> AssetAge { get; set; }
        public string Status { get; set; }
        public int OUID { get; set; }
        public int ARID { get; set; }
    }
}
