//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ARADBEntities1 : DbContext
    {
        public ARADBEntities1()
            : base("name=ARADBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AllocatedTo_t> AllocatedTo_t { get; set; }
        public DbSet<AllocationType_t> AllocationType_t { get; set; }
        public DbSet<Asset_t> Asset_t { get; set; }
        public DbSet<AssetAllocation_t> AssetAllocation_t { get; set; }
        public DbSet<AssetCategory_t> AssetCategory_t { get; set; }
        public DbSet<AssetClass_t> AssetClass_t { get; set; }
        public DbSet<AssetFamily_t> AssetFamily_t { get; set; }
        public DbSet<AssetMake_t> AssetMake_t { get; set; }
        public DbSet<AssetModel_t> AssetModel_t { get; set; }
        public DbSet<AssetOpCondition_t> AssetOpCondition_t { get; set; }
        public DbSet<AssetOtherInfo_t> AssetOtherInfo_t { get; set; }
        public DbSet<AssetPurchase_t> AssetPurchase_t { get; set; }
        public DbSet<AssetRepair_t> AssetRepair_t { get; set; }
        public DbSet<AssetRepairType_t> AssetRepairType_t { get; set; }
        public DbSet<AssetRetCriteriaConditions_t> AssetRetCriteriaConditions_t { get; set; }
        public DbSet<AssetRetirement_t> AssetRetirement_t { get; set; }
        public DbSet<AssetRetirementCriteria_t> AssetRetirementCriteria_t { get; set; }
        public DbSet<AssetStatus_t> AssetStatus_t { get; set; }
        public DbSet<AssetType_t> AssetType_t { get; set; }
        public DbSet<EmpBPS_t> EmpBPS_t { get; set; }
        public DbSet<EmpDepartments_t> EmpDepartments_t { get; set; }
        public DbSet<EmpDesignations_t> EmpDesignations_t { get; set; }
        public DbSet<EmpDivisions_t> EmpDivisions_t { get; set; }
        public DbSet<EmpStations_t> EmpStations_t { get; set; }
        public DbSet<Login_t> Login_t { get; set; }
        public DbSet<OUs_t> OUs_t { get; set; }
        public DbSet<SOUs_t> SOUs_t { get; set; }
        public DbSet<Vendor_t> Vendor_t { get; set; }
        public DbSet<AllocatedTo_v> AllocatedTo_v { get; set; }
        public DbSet<AMS2ESSP> AMS2ESSP { get; set; }
        public DbSet<Asset_v> Asset_v { get; set; }
        public DbSet<Asset4Retirement_v> Asset4Retirement_v { get; set; }
        public DbSet<AssetAllocation_v> AssetAllocation_v { get; set; }
        public DbSet<AssetAllocationReport_v> AssetAllocationReport_v { get; set; }
        public DbSet<AssetAllocationReport_v1> AssetAllocationReport_v1 { get; set; }
        public DbSet<AssetCategory_v> AssetCategory_v { get; set; }
        public DbSet<AssetClass_v> AssetClass_v { get; set; }
        public DbSet<AssetFamily_v> AssetFamily_v { get; set; }
        public DbSet<AssetMake_v> AssetMake_v { get; set; }
        public DbSet<AssetModel_v> AssetModel_v { get; set; }
        public DbSet<AssetOtherInfo_v> AssetOtherInfo_v { get; set; }
        public DbSet<AssetPurchase_v> AssetPurchase_v { get; set; }
        public DbSet<AssetPurchaseDetailsRep_v> AssetPurchaseDetailsRep_v { get; set; }
        public DbSet<AssetRepair_v> AssetRepair_v { get; set; }
        public DbSet<AssetRepairType_v> AssetRepairType_v { get; set; }
        public DbSet<AssetRetCriteriaConditions_v> AssetRetCriteriaConditions_v { get; set; }
        public DbSet<AssetRetirement_v> AssetRetirement_v { get; set; }
        public DbSet<AssetRetirementCriteria_v> AssetRetirementCriteria_v { get; set; }
        public DbSet<AssetsWithA> AssetsWithAS { get; set; }
        public DbSet<AssetType_v> AssetType_v { get; set; }
        public DbSet<Employee_v> Employee_v { get; set; }
        public DbSet<Login_v> Login_v { get; set; }
    }
}
