//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_t
    {
        public Asset_t()
        {
            this.AssetAllocation_t = new HashSet<AssetAllocation_t>();
            this.AssetOtherInfo_t = new HashSet<AssetOtherInfo_t>();
            this.AssetRepair_t = new HashSet<AssetRepair_t>();
        }
    
        public int AssetID { get; set; }
        public int TYPID { get; set; }
        public int PURID { get; set; }
        public System.DateTime weDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int OUID { get; set; }
        public Nullable<int> DisposalID { get; set; }
        public int AssetStatusID { get; set; }
        public int SOUID { get; set; }
    
        public virtual AssetStatus_t AssetStatus_t { get; set; }
        public virtual Login_t Login_t { get; set; }
        public virtual SOUs_t SOUs_t { get; set; }
        public virtual ICollection<AssetAllocation_t> AssetAllocation_t { get; set; }
        public virtual AssetPurchase_t AssetPurchase_t { get; set; }
        public virtual AssetType_t AssetType_t { get; set; }
        public virtual ICollection<AssetOtherInfo_t> AssetOtherInfo_t { get; set; }
        public virtual ICollection<AssetRepair_t> AssetRepair_t { get; set; }
    }
}
