//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetFamily_v
    {
        public int CLSID { get; set; }
        public string ClassName { get; set; }
        public int CatID { get; set; }
        public string CategoryName { get; set; }
        public int MAKID { get; set; }
        public string MakeName { get; set; }
        public int MODID { get; set; }
        public string ModelName { get; set; }
        public int FAMID { get; set; }
        public string FamilyName { get; set; }
        public int OUID { get; set; }
        public int SOUID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
