//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset4Retirement_v
    {
        public int AssetID { get; set; }
        public int CatID { get; set; }
        public string Category { get; set; }
        public string BCNo { get; set; }
        public int AssetTypeID { get; set; }
        public string AssetTypeName { get; set; }
        public int AssetPurchaseID { get; set; }
        public System.DateTime DoP { get; set; }
        public decimal UnitPrice { get; set; }
        public System.DateTime weDate { get; set; }
        public System.DateTime FromDate { get; set; }
        public string Status { get; set; }
        public string AllocationTypeName { get; set; }
        public string AllocatedToName { get; set; }
        public int VendorID { get; set; }
        public int AllocationTypeID { get; set; }
        public int AllocatedToID { get; set; }
        public int OCID { get; set; }
        public string OCName { get; set; }
        public string VendorName { get; set; }
        public int OUID { get; set; }
        public System.DateTime ToDate { get; set; }
        public int AssetStatusID { get; set; }
    }
}
