//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetPurchase_v
    {
        public int PURID { get; set; }
        public string TypeName { get; set; }
        public System.DateTime DoP { get; set; }
        public string FY { get; set; }
        public decimal UnitPrice { get; set; }
        public int NumOfUnits { get; set; }
        public int TYPID { get; set; }
        public string Status { get; set; }
        public int wPeriod { get; set; }
        public string wDMY { get; set; }
        public int VendorID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int OUID { get; set; }
        public string StkRgEntry { get; set; }
        public string FileLtrRef { get; set; }
        public int SOUID { get; set; }
        public string VendorName { get; set; }
    }
}
