//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetCategory_v
    {
        public int CLSID { get; set; }
        public string ClassName { get; set; }
        public int CatID { get; set; }
        public string CategoryName { get; set; }
        public int OUID { get; set; }
        public int SOUID { get; set; }
    }
}
