//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetRepairType_t
    {
        public AssetRepairType_t()
        {
            this.AssetRepair_t = new HashSet<AssetRepair_t>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int CatID { get; set; }
    
        public virtual AssetCategory_t AssetCategory_t { get; set; }
        public virtual ICollection<AssetRepair_t> AssetRepair_t { get; set; }
    }
}
