//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetCategory_t
    {
        public AssetCategory_t()
        {
            this.AssetRetCriteriaConditions_t = new HashSet<AssetRetCriteriaConditions_t>();
            this.AssetFamily_t = new HashSet<AssetFamily_t>();
            this.AssetMake_t = new HashSet<AssetMake_t>();
            this.AssetModel_t = new HashSet<AssetModel_t>();
            this.AssetRepairType_t = new HashSet<AssetRepairType_t>();
            this.AssetType_t = new HashSet<AssetType_t>();
        }
    
        public int CatID { get; set; }
        public string Name { get; set; }
        public int CLSID { get; set; }
        public int OUID { get; set; }
        public int SOUID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual AssetClass_t AssetClass_t { get; set; }
        public virtual SOUs_t SOUs_t { get; set; }
        public virtual OUs_t OUs_t { get; set; }
        public virtual ICollection<AssetRetCriteriaConditions_t> AssetRetCriteriaConditions_t { get; set; }
        public virtual ICollection<AssetFamily_t> AssetFamily_t { get; set; }
        public virtual ICollection<AssetMake_t> AssetMake_t { get; set; }
        public virtual ICollection<AssetModel_t> AssetModel_t { get; set; }
        public virtual ICollection<AssetRepairType_t> AssetRepairType_t { get; set; }
        public virtual ICollection<AssetType_t> AssetType_t { get; set; }
    }
}
