//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetRetirementCriteria_t
    {
        public AssetRetirementCriteria_t()
        {
            this.AssetRetCriteriaConditions_t = new HashSet<AssetRetCriteriaConditions_t>();
            this.AssetRetirement_t = new HashSet<AssetRetirement_t>();
        }
    
        public int ID { get; set; }
        public string CriteriaName { get; set; }
        public int OUID { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<AssetRetCriteriaConditions_t> AssetRetCriteriaConditions_t { get; set; }
        public virtual ICollection<AssetRetirement_t> AssetRetirement_t { get; set; }
        public virtual OUs_t OUs_t { get; set; }
    }
}
