//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetPurchaseDetailsRep_v
    {
        public Nullable<long> Sr { get; set; }
        public int PURID { get; set; }
        public int TYPID { get; set; }
        public int CLSID { get; set; }
        public string ClassName { get; set; }
        public int CatID { get; set; }
        public string Category { get; set; }
        public string MakeName { get; set; }
        public string ModelName { get; set; }
        public string Family { get; set; }
        public string AssetType { get; set; }
        public string FY { get; set; }
        public System.DateTime DoP { get; set; }
        public int NumOfUnits { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public int wPeriod { get; set; }
        public string wDMY { get; set; }
        public Nullable<System.DateTime> wEndDate { get; set; }
        public string Status { get; set; }
        public int OUID { get; set; }
        public int SOUID { get; set; }
    }
}
