//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_JobCard
    {
        public Att_JobCard()
        {
            this.Att_JobCardApp = new HashSet<Att_JobCardApp>();
        }
    
        public short JCID { get; set; }
        public string JCName { get; set; }
        public string DutyCode { get; set; }
        public Nullable<short> WorkMin { get; set; }
    
        public virtual ICollection<Att_JobCardApp> Att_JobCardApp { get; set; }
    }
}
