//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_Remark
    {
        public byte RemarkID { get; set; }
        public string RemarksName { get; set; }
        public string RemarkValue { get; set; }
        public Nullable<bool> Enable { get; set; }
    }
}
