//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_ReaderDutyCode
    {
        public Att_ReaderDutyCode()
        {
            this.Att_Reader = new HashSet<Att_Reader>();
        }
    
        public byte RdrDuty { get; set; }
        public string DutyName { get; set; }
    
        public virtual ICollection<Att_Reader> Att_Reader { get; set; }
    }
}
