//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_OTPolicy
    {
        public Att_OTPolicy()
        {
            this.HR_Employee = new HashSet<HR_Employee>();
        }
    
        public short OTPolicyID { get; set; }
        public string OTPolicyName { get; set; }
        public Nullable<bool> Enable { get; set; }
        public Nullable<bool> CalculateNOT { get; set; }
        public Nullable<bool> CalculateGZOT { get; set; }
        public Nullable<bool> CalculateRestOT { get; set; }
        public Nullable<double> PerDayOTStartLimitHour { get; set; }
        public Nullable<double> PerDayOTEndLimitHour { get; set; }
        public Nullable<double> PerDayROTStartLimitHour { get; set; }
        public Nullable<double> PerDayROTEndLimitHour { get; set; }
        public Nullable<double> PerDayGOTStartLimitHour { get; set; }
        public Nullable<double> PerDayGOTEndLimitHour { get; set; }
        public Nullable<short> MinMinutesForOneHour { get; set; }
        public Nullable<byte> DaysInMonth { get; set; }
        public Nullable<byte> DaysInWeek { get; set; }
        public Nullable<bool> AddEIinOT { get; set; }
    
        public virtual ICollection<HR_Employee> HR_Employee { get; set; }
    }
}
