//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_JobCardApp
    {
        public int JobCardAppID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<System.DateTime> DateEnded { get; set; }
        public Nullable<short> JCTypeID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> TimeBased { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<short> TotalMins { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> SupervisorID { get; set; }
        public string StatusID { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Justification { get; set; }
        public Nullable<int> CriteriaData { get; set; }
        public string JobCardCriteria { get; set; }
    
        public virtual Att_JobCard Att_JobCard { get; set; }
    }
}
