//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_OutPass
    {
        public int OPID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public string EmpDate { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<int> EditedBy { get; set; }
        public Nullable<System.DateTime> Tin1 { get; set; }
        public Nullable<System.DateTime> Tout1 { get; set; }
        public Nullable<short> Min1 { get; set; }
        public string Reason1 { get; set; }
        public Nullable<System.DateTime> Tin2 { get; set; }
        public Nullable<System.DateTime> Tout2 { get; set; }
        public Nullable<short> Min2 { get; set; }
        public string Reason2 { get; set; }
        public Nullable<System.DateTime> Tin3 { get; set; }
        public Nullable<System.DateTime> Tout3 { get; set; }
        public Nullable<short> Min3 { get; set; }
        public string Reason3 { get; set; }
        public Nullable<System.DateTime> Tin4 { get; set; }
        public Nullable<System.DateTime> Tout4 { get; set; }
        public Nullable<short> Min4 { get; set; }
        public string Reason4 { get; set; }
        public Nullable<System.DateTime> Tin5 { get; set; }
        public Nullable<System.DateTime> Tout5 { get; set; }
        public Nullable<short> Min5 { get; set; }
        public string Reason5 { get; set; }
        public Nullable<bool> Enable { get; set; }
    
        public virtual HR_Employee HR_Employee { get; set; }
    }
}
