//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_RosterDetail
    {
        public string CriteriaValueDate { get; set; }
        public Nullable<int> RosterAppID { get; set; }
        public string DutyCode { get; set; }
        public Nullable<System.TimeSpan> DutyTime { get; set; }
        public Nullable<short> WorkMin { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> OpenShift { get; set; }
        public Nullable<System.DateTime> RosterDate { get; set; }
    
        public virtual Att_RosterApplication Att_RosterApplication { get; set; }
    }
}
