//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_EmpFace
    {
        public int EmpFaceID { get; set; }
        public string EmpFace1 { get; set; }
        public string EmpFace2 { get; set; }
        public string EmpFace3 { get; set; }
        public Nullable<int> EmpID { get; set; }
    
        public virtual HR_Employee HR_Employee { get; set; }
    }
}
