//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_EmpFP
    {
        public int EmpFPID { get; set; }
        public string EmpFP1 { get; set; }
        public string EmpFP2 { get; set; }
        public string EmpFP3 { get; set; }
        public string EmpFP4 { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string EmpFP5 { get; set; }
        public Nullable<System.DateTime> CDateTime { get; set; }
    
        public virtual HR_Employee HR_Employee { get; set; }
    }
}
