//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_Reader
    {
        public Att_Reader()
        {
            this.Att_DeviceData = new HashSet<Att_DeviceData>();
        }
    
        public short RdrID { get; set; }
        public string RdrName { get; set; }
        public byte ReaderDutyCode { get; set; }
        public string IpAdd { get; set; }
        public short IpPort { get; set; }
        public byte RdrTypeID { get; set; }
        public bool Status { get; set; }
        public Nullable<short> LocID { get; set; }
        public Nullable<bool> ClearRecords { get; set; }
        public string EmailTo { get; set; }
        public string EmailCC { get; set; }
    
        public virtual ICollection<Att_DeviceData> Att_DeviceData { get; set; }
        public virtual Att_ReaderDutyCode Att_ReaderDutyCode { get; set; }
        public virtual Att_ReaderType Att_ReaderType { get; set; }
        public virtual HR_Location HR_Location { get; set; }
    }
}
