//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_Holiday
    {
        public byte HolidayID { get; set; }
        public Nullable<System.DateTime> HolidayDate { get; set; }
        public string HolidayName { get; set; }
    }
}
