//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_RFIDCard
    {
        public Att_RFIDCard()
        {
            this.VMS_VisitInfo = new HashSet<VMS_VisitInfo>();
        }
    
        public int PSerialID { get; set; }
        public string CardNo { get; set; }
        public Nullable<int> FloorID { get; set; }
        public string SerialDisplay { get; set; }
    
        public virtual VMS_Floor VMS_Floor { get; set; }
        public virtual ICollection<VMS_VisitInfo> VMS_VisitInfo { get; set; }
    }
}
