//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_DaysName
    {
        public Att_DaysName()
        {
            this.Att_Shift = new HashSet<Att_Shift>();
            this.Att_Shift1 = new HashSet<Att_Shift>();
        }
    
        public byte ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Att_Shift> Att_Shift { get; set; }
        public virtual ICollection<Att_Shift> Att_Shift1 { get; set; }
    }
}
