//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_OTDailyEntry
    {
        public int POTAID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string EmpDate { get; set; }
        public Nullable<System.DateTime> OTDate { get; set; }
        public Nullable<int> ActualOTMin { get; set; }
        public Nullable<int> ApprovedOTMin { get; set; }
        public string DutyCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<double> OTAmount { get; set; }
        public string StatusID { get; set; }
        public Nullable<System.DateTime> CDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedDTime { get; set; }
        public Nullable<int> ForwardToID { get; set; }
        public Nullable<int> SupervisorID { get; set; }
        public Nullable<int> ApprovedByID { get; set; }
        public Nullable<int> RejectByID { get; set; }
        public Nullable<int> CancelByID { get; set; }
        public Nullable<System.DateTime> PtoFCDateTime { get; set; }
        public Nullable<int> PtoFCUserID { get; set; }
        public Nullable<System.DateTime> FtoARDateTime { get; set; }
        public Nullable<int> FtoARUserID { get; set; }
        public Nullable<int> OTProcessingPeriodID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<System.DateTime> FtoFCDateTime { get; set; }
        public Nullable<int> FtoFCUserID { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public Nullable<double> TaxAmount { get; set; }
    
        public virtual HR_Employee HR_Employee { get; set; }
    }
}
