//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_MonthDataEdit
    {
        public int MID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> PayrollPeriodID { get; set; }
        public Nullable<System.DateTime> DateEdit { get; set; }
        public Nullable<double> OldTotalDays { get; set; }
        public Nullable<double> OldPaidDays { get; set; }
        public Nullable<double> OldAbsentDays { get; set; }
        public Nullable<double> NewTotalDays { get; set; }
        public Nullable<double> NewPaidDays { get; set; }
        public Nullable<double> NewAbsentDays { get; set; }
        public Nullable<double> OldOTMin { get; set; }
        public Nullable<double> NewOTMin { get; set; }
        public Nullable<double> NewSH { get; set; }
        public Nullable<double> OldSH { get; set; }
        public Nullable<int> UserID { get; set; }
        public string NewRemarks { get; set; }
        public Nullable<int> NewLocID { get; set; }
        public Nullable<int> OldLocID { get; set; }
    }
}
