//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_Shift
    {
        public Att_Shift()
        {
            this.Att_RosterApplication = new HashSet<Att_RosterApplication>();
            this.Att_ShiftChanged = new HashSet<Att_ShiftChanged>();
            this.Att_ShiftChngedEmp = new HashSet<Att_ShiftChngedEmp>();
            this.HR_Employee = new HashSet<HR_Employee>();
        }
    
        public short ShftID { get; set; }
        public string ShiftName { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public byte DayOff1 { get; set; }
        public byte DayOff2 { get; set; }
        public short MonMin { get; set; }
        public short TueMin { get; set; }
        public short WedMin { get; set; }
        public short ThuMin { get; set; }
        public short FriMin { get; set; }
        public short SatMin { get; set; }
        public short SunMin { get; set; }
        public Nullable<short> LateIn { get; set; }
        public Nullable<short> EarlyIn { get; set; }
        public Nullable<short> EarlyOut { get; set; }
        public Nullable<short> LateOut { get; set; }
        public Nullable<short> OverTimeMin { get; set; }
        public Nullable<short> MinHrs { get; set; }
        public Nullable<bool> HasBreak { get; set; }
        public Nullable<short> BreakMin { get; set; }
        public Nullable<short> HalfDayBreakMin { get; set; }
        public Nullable<bool> GZDays { get; set; }
        public Nullable<bool> OpenShift { get; set; }
        public Nullable<bool> RoundOffWorkMin { get; set; }
        public Nullable<bool> SubtractLOFromWork { get; set; }
        public Nullable<bool> SubtractEIFromWork { get; set; }
        public Nullable<bool> PresentAtIN { get; set; }
        public Nullable<bool> CalDiffOnly { get; set; }
    
        public virtual Att_DaysName Att_DaysName { get; set; }
        public virtual Att_DaysName Att_DaysName1 { get; set; }
        public virtual ICollection<Att_RosterApplication> Att_RosterApplication { get; set; }
        public virtual ICollection<Att_ShiftChanged> Att_ShiftChanged { get; set; }
        public virtual ICollection<Att_ShiftChngedEmp> Att_ShiftChngedEmp { get; set; }
        public virtual ICollection<HR_Employee> HR_Employee { get; set; }
    }
}
