//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_OTDForward
    {
        public int POTFID { get; set; }
        public Nullable<int> OTDailyEntryID { get; set; }
        public Nullable<int> ForwardFrom { get; set; }
        public Nullable<int> ForwardTo { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> ProcessPeriodID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CliamedOTMins { get; set; }
        public string OldStatusID { get; set; }
        public string Operation { get; set; }
        public string NewStatusID { get; set; }
        public Nullable<System.DateTime> CDTime { get; set; }
        public Nullable<int> OTPeriodID { get; set; }
    }
}
