//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_OTDebit
    {
        public int PDID { get; set; }
        public Nullable<int> BOTDivID { get; set; }
        public Nullable<int> FinYearID { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Remarks { get; set; }
    }
}
