//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Designation
    {
        public HR_Designation()
        {
            this.HR_Employee = new HashSet<HR_Employee>();
        }
    
        public short DesgID { get; set; }
        public string DesignationName { get; set; }
        public string ODesigID { get; set; }
        public string OCommonName { get; set; }
    
        public virtual ICollection<HR_Employee> HR_Employee { get; set; }
    }
}
