//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Department
    {
        public HR_Department()
        {
            this.HR_Employee = new HashSet<HR_Employee>();
            this.HR_Section = new HashSet<HR_Section>();
        }
    
        public short DeptID { get; set; }
        public string DepartmentName { get; set; }
        public string ODeptID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<HR_Employee> HR_Employee { get; set; }
        public virtual ICollection<HR_Section> HR_Section { get; set; }
    }
}
