//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_EmpACR_Status
    {
        public int SR { get; set; }
        public string EMP { get; set; }
        public string NAME { get; set; }
        public string DESIGNATION { get; set; }
        public string PRD_FRM { get; set; }
        public string PRD_TO { get; set; }
        public string IO { get; set; }
        public string CO { get; set; }
        public string STATUS { get; set; }
        public string REMARKS { get; set; }
        public string TEST_STATUS { get; set; }
    }
}
