//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Emp_Qualification
    {
        public int QualificationID { get; set; }
        public int EmployeeID { get; set; }
        public string StartSession { get; set; }
        public string EndSession { get; set; }
        public string Specialization { get; set; }
        public string Grade { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string DocumentPath { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string Degree { get; set; }
        public string Institute { get; set; }
        public string distinction { get; set; }
        public string Source_of_Data { get; set; }
    }
}
