//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Emp_Notification
    {
        public int NotificationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string RoleType { get; set; }
        public string Notification { get; set; }
        public Nullable<int> NotificationTypeID { get; set; }
        public string NotificationURL { get; set; }
        public bool UserSpecific { get; set; }
        public Nullable<int> RecordID { get; set; }
        public Nullable<int> ActionBY { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
    }
}
