//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_GradeHistory
    {
        public int PID { get; set; }
        public short GrdID { get; set; }
        public string GradeName { get; set; }
        public string OGradeID { get; set; }
        public Nullable<double> NormalOTAmount { get; set; }
        public Nullable<double> RestOTAmount { get; set; }
        public Nullable<double> GZOTAmount { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> CDateTime { get; set; }
    }
}
