//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_ListType
    {
        public HR_ListType()
        {
            this.HR_ListEntry = new HashSet<HR_ListEntry>();
        }
    
        public int intListTypeId { get; set; }
        public string vchListName { get; set; }
        public string VchListDescription { get; set; }
        public bool bitActive { get; set; }
    
        public virtual ICollection<HR_ListEntry> HR_ListEntry { get; set; }
    }
}
