//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Location
    {
        public HR_Location()
        {
            this.Att_Reader = new HashSet<Att_Reader>();
            this.HR_Employee = new HashSet<HR_Employee>();
        }
    
        public short LocID { get; set; }
        public string LocationName { get; set; }
        public string OLocationID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<Att_Reader> Att_Reader { get; set; }
        public virtual ICollection<HR_Employee> HR_Employee { get; set; }
    }
}
