//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_ListEntry
    {
        public int intListEntryId { get; set; }
        public int intListTypeId { get; set; }
        public string vchListEntryName { get; set; }
        public string vchEntryDescription { get; set; }
        public bool bitActive { get; set; }
        public Nullable<int> intListParentId { get; set; }
    
        public virtual HR_ListType HR_ListType { get; set; }
    }
}
