//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_LeaveReminders
    {
        public int ReminderID { get; set; }
        public Nullable<int> LEAVEID { get; set; }
        public Nullable<int> SRNO { get; set; }
        public string REMINDERDATE { get; set; }
        public string REMINDESTO { get; set; }
    }
}
