//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_LeaveModule
    {
        public int MODULEID { get; set; }
        public string NAME { get; set; }
        public string NAV_URL { get; set; }
        public string IMAGE { get; set; }
        public string PARENTID { get; set; }
        public Nullable<int> ISADMIN { get; set; }
        public Nullable<int> DISPORDER { get; set; }
    }
}
