//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_LeaveType
    {
        public int LeaveTypeID { get; set; }
        public string CO { get; set; }
        public string LEAVETYPE { get; set; }
        public string DESCR { get; set; }
        public Nullable<int> HIDE { get; set; }
        public Nullable<int> ISEARNED { get; set; }
        public Nullable<int> ISDUTY { get; set; }
    }
}
