//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_SMTP
    {
        public int ID { get; set; }
        public string SMTPServer { get; set; }
        public string SMTPPort { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
    }
}
