//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Section
    {
        public HR_Section()
        {
            this.HR_Employee = new HashSet<HR_Employee>();
        }
    
        public short SecID { get; set; }
        public string SectionName { get; set; }
        public Nullable<short> DepartmentID { get; set; }
        public string OSecID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<short> LocID { get; set; }
        public string OLocID { get; set; }
    
        public virtual HR_Department HR_Department { get; set; }
        public virtual ICollection<HR_Employee> HR_Employee { get; set; }
    }
}
