//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_v
    {
        public int ID { get; set; }
        public string LoginID { get; set; }
        public string LoginPwd { get; set; }
        public string UserType { get; set; }
        public int OUID { get; set; }
        public int SOUID { get; set; }
        public string OUName { get; set; }
        public string SOUName { get; set; }
    }
}
