//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRMEntities : DbContext
    {
        public HRMEntities()
            : base("name=HRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccessUser> AccessUsers { get; set; }
        public DbSet<Att_DailyAttendance> Att_DailyAttendance { get; set; }
        public DbSet<Att_DaysName> Att_DaysName { get; set; }
        public DbSet<Att_DeviceData> Att_DeviceData { get; set; }
        public DbSet<Att_DeviceDataError> Att_DeviceDataError { get; set; }
        public DbSet<Att_DownloadTime> Att_DownloadTime { get; set; }
        public DbSet<Att_EmpFace> Att_EmpFace { get; set; }
        public DbSet<Att_EmpFP> Att_EmpFP { get; set; }
        public DbSet<Att_Holiday> Att_Holiday { get; set; }
        public DbSet<Att_JobCard> Att_JobCard { get; set; }
        public DbSet<Att_JobCardApp> Att_JobCardApp { get; set; }
        public DbSet<Att_JobCardDetail> Att_JobCardDetail { get; set; }
        public DbSet<Att_Leave> Att_Leave { get; set; }
        public DbSet<Att_ManualEdit> Att_ManualEdit { get; set; }
        public DbSet<Att_MonthData> Att_MonthData { get; set; }
        public DbSet<Att_MonthDataEdit> Att_MonthDataEdit { get; set; }
        public DbSet<Att_MonthlyOTEntry> Att_MonthlyOTEntry { get; set; }
        public DbSet<Att_OPName> Att_OPName { get; set; }
        public DbSet<Att_OTDailyEntry> Att_OTDailyEntry { get; set; }
        public DbSet<Att_OTDForward> Att_OTDForward { get; set; }
        public DbSet<Att_OTPolicy> Att_OTPolicy { get; set; }
        public DbSet<Att_OTStatus> Att_OTStatus { get; set; }
        public DbSet<Att_OutPass> Att_OutPass { get; set; }
        public DbSet<Att_ProcessDate> Att_ProcessDate { get; set; }
        public DbSet<Att_ProcessRequest> Att_ProcessRequest { get; set; }
        public DbSet<Att_Reader> Att_Reader { get; set; }
        public DbSet<Att_ReaderDutyCode> Att_ReaderDutyCode { get; set; }
        public DbSet<Att_ReaderType> Att_ReaderType { get; set; }
        public DbSet<Att_Remark> Att_Remark { get; set; }
        public DbSet<Att_RFIDCard> Att_RFIDCard { get; set; }
        public DbSet<Att_RosterApplication> Att_RosterApplication { get; set; }
        public DbSet<Att_RosterDetail> Att_RosterDetail { get; set; }
        public DbSet<Att_RosterType> Att_RosterType { get; set; }
        public DbSet<Att_ServiceLog> Att_ServiceLog { get; set; }
        public DbSet<Att_Setting> Att_Setting { get; set; }
        public DbSet<Att_Shift> Att_Shift { get; set; }
        public DbSet<Att_ShiftChanged> Att_ShiftChanged { get; set; }
        public DbSet<Att_ShiftChngedEmp> Att_ShiftChngedEmp { get; set; }
        public DbSet<Att_TemplatesFP> Att_TemplatesFP { get; set; }
        public DbSet<Audit_Form> Audit_Form { get; set; }
        public DbSet<Audit_Log> Audit_Log { get; set; }
        public DbSet<BG_OTCredit> BG_OTCredit { get; set; }
        public DbSet<BG_OTDebit> BG_OTDebit { get; set; }
        public DbSet<BG_OTDivision> BG_OTDivision { get; set; }
        public DbSet<FocalUser> FocalUsers { get; set; }
        public DbSet<HR_City> HR_City { get; set; }
        public DbSet<HR_Department> HR_Department { get; set; }
        public DbSet<HR_Designation> HR_Designation { get; set; }
        public DbSet<HR_Emp_Communication> HR_Emp_Communication { get; set; }
        public DbSet<HR_Emp_Dependents> HR_Emp_Dependents { get; set; }
        public DbSet<HR_Emp_Experience> HR_Emp_Experience { get; set; }
        public DbSet<HR_Emp_Notification> HR_Emp_Notification { get; set; }
        public DbSet<HR_Emp_Qualification> HR_Emp_Qualification { get; set; }
        public DbSet<HR_EmpACR_Status> HR_EmpACR_Status { get; set; }
        public DbSet<HR_EmpAppreciations> HR_EmpAppreciations { get; set; }
        public DbSet<HR_EmpBloodGroup> HR_EmpBloodGroup { get; set; }
        public DbSet<HR_EmpChange> HR_EmpChange { get; set; }
        public DbSet<HR_EmpGender> HR_EmpGender { get; set; }
        public DbSet<HR_EmpImage> HR_EmpImage { get; set; }
        public DbSet<HR_Employee> HR_Employee { get; set; }
        public DbSet<HR_EmployeeHistory> HR_EmployeeHistory { get; set; }
        public DbSet<HR_EmpPromotions> HR_EmpPromotions { get; set; }
        public DbSet<HR_EmpStatus> HR_EmpStatus { get; set; }
        public DbSet<HR_EmpTrainings> HR_EmpTrainings { get; set; }
        public DbSet<HR_EmpTranfers> HR_EmpTranfers { get; set; }
        public DbSet<HR_EmpType> HR_EmpType { get; set; }
        public DbSet<HR_EmpWarnings> HR_EmpWarnings { get; set; }
        public DbSet<HR_Grade> HR_Grade { get; set; }
        public DbSet<HR_GradeHistory> HR_GradeHistory { get; set; }
        public DbSet<HR_LeaveModule> HR_LeaveModule { get; set; }
        public DbSet<HR_LeaveRec> HR_LeaveRec { get; set; }
        public DbSet<HR_LeaveReminders> HR_LeaveReminders { get; set; }
        public DbSet<HR_LeaveReq> HR_LeaveReq { get; set; }
        public DbSet<HR_LeaveType> HR_LeaveType { get; set; }
        public DbSet<HR_ListEntry> HR_ListEntry { get; set; }
        public DbSet<HR_ListType> HR_ListType { get; set; }
        public DbSet<HR_Location> HR_Location { get; set; }
        public DbSet<HR_MartialStatus> HR_MartialStatus { get; set; }
        public DbSet<HR_OracleDB> HR_OracleDB { get; set; }
        public DbSet<HR_Section> HR_Section { get; set; }
        public DbSet<HR_SMTP> HR_SMTP { get; set; }
        public DbSet<PR_FinYear> PR_FinYear { get; set; }
        public DbSet<PR_PayrollPeriod> PR_PayrollPeriod { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TBLLOG> TBLLOGs { get; set; }
        public DbSet<TBLLOG_TYPE> TBLLOG_TYPE { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserRoleData> UserRoleDatas { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
        public DbSet<VMS_BanCNIC> VMS_BanCNIC { get; set; }
        public DbSet<VMS_CreateVisitorSMS> VMS_CreateVisitorSMS { get; set; }
        public DbSet<VMS_Floor> VMS_Floor { get; set; }
        public DbSet<VMS_Reason> VMS_Reason { get; set; }
        public DbSet<VMS_SMSSend> VMS_SMSSend { get; set; }
        public DbSet<VMS_SpecialVisitor> VMS_SpecialVisitor { get; set; }
        public DbSet<VMS_SVisitor> VMS_SVisitor { get; set; }
        public DbSet<VMS_VisitDevice> VMS_VisitDevice { get; set; }
        public DbSet<VMS_VisitInfo> VMS_VisitInfo { get; set; }
        public DbSet<VMS_VisitorInfo> VMS_VisitorInfo { get; set; }
        public DbSet<VMS_VisitorPhoto> VMS_VisitorPhoto { get; set; }
        public DbSet<VMS_VisitSMS> VMS_VisitSMS { get; set; }
        public DbSet<VMS_VisitType> VMS_VisitType { get; set; }
        public DbSet<ZData> ZDatas { get; set; }
        public DbSet<EmpView> EmpViews { get; set; }
        public DbSet<ViewAttData> ViewAttDatas { get; set; }
        public DbSet<ViewAttDataDetail> ViewAttDataDetails { get; set; }
        public DbSet<ViewAttMonthlySummary> ViewAttMonthlySummaries { get; set; }
        public DbSet<ViewAttOTForward> ViewAttOTForwards { get; set; }
        public DbSet<ViewAttShiftChngeEmp> ViewAttShiftChngeEmps { get; set; }
        public DbSet<ViewAuditLog> ViewAuditLogs { get; set; }
        public DbSet<ViewBGCredit> ViewBGCredits { get; set; }
        public DbSet<ViewBGOTDebit> ViewBGOTDebits { get; set; }
        public DbSet<ViewBGOTDivision> ViewBGOTDivisions { get; set; }
        public DbSet<ViewDailyOTEntry> ViewDailyOTEntries { get; set; }
        public DbSet<ViewEmpAccess> ViewEmpAccesses { get; set; }
        public DbSet<ViewEmpAppreciation> ViewEmpAppreciations { get; set; }
        public DbSet<ViewEmpCommunication> ViewEmpCommunications { get; set; }
        public DbSet<ViewEmpDependent> ViewEmpDependents { get; set; }
        public DbSet<ViewEmpHistory> ViewEmpHistories { get; set; }
        public DbSet<ViewEmpPreJobHistory> ViewEmpPreJobHistories { get; set; }
        public DbSet<ViewEmpQualification> ViewEmpQualifications { get; set; }
        public DbSet<ViewEmpTraining> ViewEmpTrainings { get; set; }
        public DbSet<ViewEmpTrainingReport> ViewEmpTrainingReports { get; set; }
        public DbSet<ViewEMPTransfer> ViewEMPTransfers { get; set; }
        public DbSet<ViewEmpWarning> ViewEmpWarnings { get; set; }
        public DbSet<ViewHREmpChange> ViewHREmpChanges { get; set; }
        public DbSet<ViewHRSection> ViewHRSections { get; set; }
        public DbSet<ViewJobCard> ViewJobCards { get; set; }
        public DbSet<ViewJobCardEmp> ViewJobCardEmps { get; set; }
        public DbSet<ViewOTMonthlySummary> ViewOTMonthlySummaries { get; set; }
        public DbSet<ViewPollData> ViewPollDatas { get; set; }
        public DbSet<ViewReportQualification> ViewReportQualifications { get; set; }
        public DbSet<ViewSVisitorEmp> ViewSVisitorEmps { get; set; }
        public DbSet<ViewUserEmp> ViewUserEmps { get; set; }
        public DbSet<ViewUserEmpSimple> ViewUserEmpSimples { get; set; }
        public DbSet<ViewVisitEmp> ViewVisitEmps { get; set; }
        public DbSet<ViewVisitorsVisit> ViewVisitorsVisits { get; set; }
    }
}
