//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_PayrollPeriod
    {
        public PR_PayrollPeriod()
        {
            this.Att_MonthData = new HashSet<Att_MonthData>();
            this.Att_MonthlyOTEntry = new HashSet<Att_MonthlyOTEntry>();
        }
    
        public int PID { get; set; }
        public string PName { get; set; }
        public Nullable<System.DateTime> PStartDate { get; set; }
        public Nullable<System.DateTime> PEndDate { get; set; }
        public string PStageID { get; set; }
        public Nullable<int> FinYearID { get; set; }
        public Nullable<System.DateTime> SupervisorCutOffDate { get; set; }
        public Nullable<System.DateTime> RecommendCutOffDate { get; set; }
        public Nullable<System.DateTime> ApprovedCutOffDate { get; set; }
        public Nullable<bool> ProcessedOT { get; set; }
    
        public virtual ICollection<Att_MonthData> Att_MonthData { get; set; }
        public virtual ICollection<Att_MonthlyOTEntry> Att_MonthlyOTEntry { get; set; }
    }
}
