//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLLOG
    {
        public int LOGID { get; set; }
        public Nullable<int> LOGTYPID { get; set; }
        public Nullable<System.DateTime> LOGTIME { get; set; }
        public string USERID { get; set; }
        public string REMARKS { get; set; }
        public Nullable<int> REFID { get; set; }
        public string IPADDRESS { get; set; }
    }
}
