//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string UserType { get; set; }
        public Nullable<bool> Status { get; set; }
        public string UI_Theme { get; set; }
        public Nullable<bool> HRRequest { get; set; }
        public Nullable<bool> HRReport { get; set; }
        public int IsAdmin { get; set; }
        public Nullable<int> lmsAdmin { get; set; }
    
        public virtual HR_Employee HR_Employee { get; set; }
    }
}
