//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmpQualification
    {
        public int QualificationID { get; set; }
        public int EmployeeID { get; set; }
        public string StartSession { get; set; }
        public string EndSession { get; set; }
        public string Specialization { get; set; }
        public string Grade { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string FirstName { get; set; }
        public string FullName { get; set; }
        public string DocumentPath { get; set; }
        public string distinction { get; set; }
        public string Institute { get; set; }
        public string Degree { get; set; }
        public string CNICNo { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string DesignationName { get; set; }
        public string DepartmentName { get; set; }
        public string LocationName { get; set; }
        public short DesgID { get; set; }
        public short DeptID { get; set; }
        public short LocID { get; set; }
        public string Status { get; set; }
    }
}
