//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmpWarning
    {
        public int WarningID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> Warnings___Explations_Date { get; set; }
        public string Warnings___Explations_Reason { get; set; }
        public string Warnings___Explations_From { get; set; }
        public string DocumentPath { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string Source_of_Data { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string FullName { get; set; }
        public string Status { get; set; }
    }
}
