//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAttShiftChngeEmp
    {
        public string ShiftName { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public string DesignationName { get; set; }
        public string TypeName { get; set; }
        public string SectionName { get; set; }
        public string DepartmentName { get; set; }
        public string LocationName { get; set; }
        public string EmpNo { get; set; }
        public string FullName { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<short> ShiftID { get; set; }
        public int ID { get; set; }
    }
}
