//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewHRSection
    {
        public string DepartmentName { get; set; }
        public short DeptID { get; set; }
        public string SectionName { get; set; }
        public short SecID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<short> LocID { get; set; }
    }
}
