//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewHREmpChange
    {
        public Nullable<short> DesignationID { get; set; }
        public Nullable<short> LocationID { get; set; }
        public Nullable<short> SectionID { get; set; }
        public Nullable<short> EmpTypeID { get; set; }
        public Nullable<short> GradeID { get; set; }
        public string SectionName { get; set; }
        public Nullable<short> DeptID { get; set; }
        public string DepartmentName { get; set; }
        public string LocationName { get; set; }
        public string TypeName { get; set; }
        public string GradeName { get; set; }
        public string DesignationName { get; set; }
        public string CardNo { get; set; }
        public string PinCode { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public Nullable<bool> FaceTemp { get; set; }
        public Nullable<int> FPTemp { get; set; }
        public Nullable<bool> ProcessAttendance { get; set; }
        public Nullable<short> OTPolicyID { get; set; }
        public string ChangeStageID { get; set; }
        public int EmployeeID { get; set; }
        public int FPID { get; set; }
        public string EmpNo { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string FathersName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CNICNo { get; set; }
        public string BloodGroup { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> EmpImage { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string LandLine { get; set; }
        public string Country { get; set; }
        public string MobileNo { get; set; }
        public string EmergencyContactNo { get; set; }
        public string EmailID { get; set; }
        public string OfficialContactNo { get; set; }
        public string Status { get; set; }
        public string OfficialEmailID { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string ChangeType { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
