//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewBGOTDivision
    {
        public short DeptID { get; set; }
        public string DepartmentName { get; set; }
        public int PBDivID { get; set; }
        public Nullable<int> FinYear { get; set; }
        public int PFinYearID { get; set; }
        public string FinYearName { get; set; }
        public Nullable<short> DivID { get; set; }
        public Nullable<int> TotalBudget { get; set; }
        public Nullable<int> PaidBudget { get; set; }
        public Nullable<int> RemainingBudget { get; set; }
    }
}
