//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewOTMonthlySummary
    {
        public Nullable<int> PayrollPeriodID { get; set; }
        public int PMOTID { get; set; }
        public string StatusID { get; set; }
        public Nullable<double> NormalOT { get; set; }
        public Nullable<double> NormalOTAmount { get; set; }
        public Nullable<double> RestOT { get; set; }
        public Nullable<double> RestOTAmount { get; set; }
        public Nullable<double> GZOT { get; set; }
        public Nullable<double> GZOTAmount { get; set; }
        public Nullable<double> TotalOT { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string PName { get; set; }
        public Nullable<System.DateTime> PStartDate { get; set; }
        public Nullable<System.DateTime> PEndDate { get; set; }
        public string PStageID { get; set; }
        public Nullable<int> PID { get; set; }
    }
}
