//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAttData
    {
        public Nullable<int> EmpID { get; set; }
        public string DesignationName { get; set; }
        public string TypeName { get; set; }
        public string ShiftName { get; set; }
        public string SectionName { get; set; }
        public string DepartmentName { get; set; }
        public string LocationName { get; set; }
        public Nullable<short> DeptID { get; set; }
        public string GradeName { get; set; }
        public Nullable<short> GrdID { get; set; }
        public Nullable<short> ShftID { get; set; }
        public Nullable<short> TypID { get; set; }
        public Nullable<short> LocID { get; set; }
        public string EmpNo { get; set; }
        public string MiddleName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string FathersName { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public Nullable<short> SecID { get; set; }
        public Nullable<System.DateTime> AttDate { get; set; }
        public string DutyCode { get; set; }
        public Nullable<System.TimeSpan> DutyTime { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public Nullable<short> WorkMin { get; set; }
        public Nullable<double> PDays { get; set; }
        public Nullable<double> AbDays { get; set; }
        public Nullable<double> LeaveDays { get; set; }
        public Nullable<short> LateIn { get; set; }
        public Nullable<short> LateOut { get; set; }
        public Nullable<short> EarlyIn { get; set; }
        public Nullable<short> EarlyOut { get; set; }
        public Nullable<short> ExtraMin { get; set; }
        public Nullable<short> NOTMin { get; set; }
        public Nullable<short> GZOTMin { get; set; }
        public Nullable<short> BreakMin { get; set; }
        public Nullable<short> TotalShortMin { get; set; }
        public Nullable<short> SLMin { get; set; }
        public Nullable<bool> StatusP { get; set; }
        public Nullable<bool> StatusAB { get; set; }
        public Nullable<bool> StatusLI { get; set; }
        public Nullable<bool> StatusLO { get; set; }
        public Nullable<bool> StatusEI { get; set; }
        public Nullable<bool> StatusEO { get; set; }
        public Nullable<bool> StatusOT { get; set; }
        public Nullable<bool> StatusGZOT { get; set; }
        public Nullable<bool> StatusGZ { get; set; }
        public Nullable<bool> StatusDO { get; set; }
        public Nullable<bool> StatusSL { get; set; }
        public Nullable<bool> StatusOD { get; set; }
        public Nullable<bool> StatusHL { get; set; }
        public Nullable<bool> StatusLeave { get; set; }
        public Nullable<bool> StatusMN { get; set; }
        public Nullable<bool> StatusIN { get; set; }
        public Nullable<bool> StatusBreak { get; set; }
        public Nullable<short> ShifMin { get; set; }
        public Nullable<short> BreakMins { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> StatusROT { get; set; }
        public Nullable<short> ROTMin { get; set; }
        public string EmpDate { get; set; }
    }
}
