//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewUserEmpSimple
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string FullName { get; set; }
        public string DesignationName { get; set; }
        public string OCommonName { get; set; }
        public string UserType { get; set; }
    }
}
