//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAttOTForward
    {
        public Nullable<int> POTAID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmpNo { get; set; }
        public string GradeName { get; set; }
        public Nullable<int> ForwardToID { get; set; }
        public string ForwardUserName { get; set; }
        public string ForwardUserType { get; set; }
        public Nullable<int> SupervisorID { get; set; }
        public string SupervisorUserType { get; set; }
        public string SupervidorUserName { get; set; }
        public string StatusName { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string ApprovedUserName { get; set; }
        public int POTFID { get; set; }
        public string ForwardFromUserName { get; set; }
        public Nullable<int> ForwardFrom { get; set; }
        public Nullable<int> ForwardTo { get; set; }
        public string ForwardToUserName { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public string CreatedUserName { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
