//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewVisitEmp
    {
        public Nullable<short> DesgID { get; set; }
        public string DesignationName { get; set; }
        public Nullable<short> TypID { get; set; }
        public string TypeName { get; set; }
        public Nullable<short> ShftID { get; set; }
        public string ShiftName { get; set; }
        public Nullable<short> GrdID { get; set; }
        public string GradeName { get; set; }
        public string SectionName { get; set; }
        public Nullable<short> DeptID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<short> LocID { get; set; }
        public string LocationName { get; set; }
        public string EmpNo { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string FathersName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CNICNo { get; set; }
        public string BloodGroup { get; set; }
        public string MaritalStatus { get; set; }
        public string Address { get; set; }
        public Nullable<int> EmpImage { get; set; }
        public string Country { get; set; }
        public string LandLine { get; set; }
        public string MobileNo { get; set; }
        public string EmergencyContactNo { get; set; }
        public string EmailID { get; set; }
        public string OfficialContactNo { get; set; }
        public Nullable<short> SecID { get; set; }
        public Nullable<bool> ProcessAttendance { get; set; }
        public string Status { get; set; }
        public string VName { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public int VisitorID { get; set; }
        public int PVisitID { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public string Remark { get; set; }
        public string OtherDetail { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string VisitorCardNo { get; set; }
        public int PVisitorID { get; set; }
        public string ReasonName { get; set; }
        public string VComapny { get; set; }
        public string VisitorCNIC { get; set; }
        public string PhoneNo { get; set; }
        public string VAddress { get; set; }
        public string VGender { get; set; }
        public string VisitorType { get; set; }
        public string VDesigName { get; set; }
        public string VSectionName { get; set; }
        public string VReason { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> PSerialID { get; set; }
        public string FloorName { get; set; }
        public Nullable<int> FloorID { get; set; }
        public Nullable<int> RFCardID { get; set; }
        public string CardNo { get; set; }
        public string SerialDisplay { get; set; }
        public Nullable<int> VisitTypeID { get; set; }
        public string PVisitTypeName { get; set; }
        public Nullable<bool> Schedule { get; set; }
        public Nullable<bool> IsVehicleOrPerson { get; set; }
        public Nullable<bool> VehicleAccess { get; set; }
        public Nullable<bool> IsManual { get; set; }
        public Nullable<bool> SendRemarksInMessage { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string OtherReasonRemarks { get; set; }
        public string VVCompany { get; set; }
        public Nullable<int> TotalPerson { get; set; }
    }
}
