//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmpAccess
    {
        public short RdrID { get; set; }
        public Nullable<int> ReaderID { get; set; }
        public string RdrName { get; set; }
        public string IpAdd { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public string SectionName { get; set; }
        public string DepartmentName { get; set; }
        public string ShiftName { get; set; }
        public string TypeName { get; set; }
        public string LocationName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    }
}
