//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewUserEmp
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string UserType { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmpNo { get; set; }
        public Nullable<int> FPID { get; set; }
        public string FirstName { get; set; }
        public string FullName { get; set; }
        public string FathersName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CNICNo { get; set; }
        public string EmailID { get; set; }
        public string OfficialEmailID { get; set; }
        public string EmpStatus { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string GradeName { get; set; }
        public string OGradeID { get; set; }
        public string OSecID { get; set; }
        public Nullable<short> DepartmentID { get; set; }
        public string SectionName { get; set; }
        public string LocationName { get; set; }
        public Nullable<short> LocID { get; set; }
        public string ODesigID { get; set; }
        public string DesignationName { get; set; }
        public Nullable<short> DesgID { get; set; }
        public Nullable<short> EmpTypeID { get; set; }
        public string TypeName { get; set; }
        public Nullable<short> TypID { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> ReportingToID { get; set; }
        public Nullable<short> SectionID { get; set; }
        public string UI_Theme { get; set; }
        public Nullable<bool> HRRequest { get; set; }
        public Nullable<bool> HRReport { get; set; }
        public int IsAdmin { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string OfficialContactNo { get; set; }
        public Nullable<int> lmsAdmin { get; set; }
        public string PUTID { get; set; }
        public string UTypeName { get; set; }
        public Nullable<bool> CanEdit { get; set; }
        public Nullable<bool> CanDelete { get; set; }
        public Nullable<bool> CanView { get; set; }
        public Nullable<bool> CanAdd { get; set; }
        public Nullable<bool> MAttProcess { get; set; }
        public Nullable<bool> MOption { get; set; }
        public Nullable<bool> MAttDevice { get; set; }
        public Nullable<bool> MAttDeviceUtility { get; set; }
        public Nullable<bool> MAttEditAttendance { get; set; }
        public Nullable<bool> MAttJobCard { get; set; }
        public Nullable<bool> MAttShift { get; set; }
        public Nullable<bool> MAttPolicy { get; set; }
        public Nullable<bool> MAttDownloadTime { get; set; }
        public Nullable<bool> MAttHoliday { get; set; }
        public Nullable<bool> MAttOTPolicy { get; set; }
        public Nullable<bool> MAttOTCreate { get; set; }
        public Nullable<bool> MAttOTEdit { get; set; }
        public Nullable<bool> MAttLeaves { get; set; }
        public Nullable<bool> MAttRoster { get; set; }
        public Nullable<bool> MHRCompHierarchy { get; set; }
        public Nullable<bool> MUser { get; set; }
        public Nullable<bool> MGrade { get; set; }
        public Nullable<bool> MHREmpA { get; set; }
        public Nullable<bool> MHREmpE { get; set; }
        public Nullable<bool> MHREmpV { get; set; }
        public Nullable<bool> MHREmpD { get; set; }
        public Nullable<bool> MHREmployee { get; set; }
        public Nullable<bool> MHREmpPersonal { get; set; }
        public Nullable<bool> MHREmpJob { get; set; }
        public Nullable<bool> MHREmpAtt { get; set; }
        public Nullable<bool> HRModule { get; set; }
        public Nullable<bool> HREmpType { get; set; }
        public Nullable<bool> HRLocation { get; set; }
        public Nullable<bool> HRDeptartment { get; set; }
        public Nullable<bool> HRDesignation { get; set; }
        public Nullable<bool> HRSection { get; set; }
        public Nullable<bool> AttendanceModule { get; set; }
        public Nullable<bool> VisitorApplication { get; set; }
        public Nullable<bool> VisitorEntry { get; set; }
        public Nullable<bool> VisitorSupervisor { get; set; }
        public Nullable<bool> OTBudget { get; set; }
        public Nullable<bool> OTBudgetCreditDebit { get; set; }
        public Nullable<bool> VisitorModule { get; set; }
    }
}
