//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewSVisitorEmp
    {
        public Nullable<int> EmployeeID { get; set; }
        public string VisitorName { get; set; }
        public string Company { get; set; }
        public string VehicleAccess { get; set; }
        public string VehicleNo { get; set; }
        public Nullable<System.DateTime> CDateTime { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Status { get; set; }
        public string DesignationName { get; set; }
        public string FullName { get; set; }
        public int ID { get; set; }
        public Nullable<System.TimeSpan> ArrivalTime { get; set; }
        public Nullable<System.DateTime> Arrival_Date { get; set; }
    }
}
