//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAttMonthlySummary
    {
        public Nullable<int> EmployeeID { get; set; }
        public int AttMnID { get; set; }
        public Nullable<double> TotalDays { get; set; }
        public Nullable<double> WorkDays { get; set; }
        public Nullable<double> PreDays { get; set; }
        public Nullable<double> AbDays { get; set; }
        public Nullable<double> RestDays { get; set; }
        public Nullable<double> GZDays { get; set; }
        public Nullable<double> LeaveDays { get; set; }
        public Nullable<short> TotalShortMins { get; set; }
        public Nullable<double> HalfLeavesDay { get; set; }
        public Nullable<double> HalfAbsentDay { get; set; }
        public Nullable<double> CLDay { get; set; }
        public Nullable<double> ALDay { get; set; }
        public Nullable<double> CPLDay { get; set; }
        public Nullable<double> GZPresentDays { get; set; }
        public Nullable<double> RestPresentDays { get; set; }
        public Nullable<double> OfficialDutyDays { get; set; }
        public Nullable<short> TEarlyIn { get; set; }
        public Nullable<short> TEarlyOut { get; set; }
        public Nullable<short> TLateIn { get; set; }
        public Nullable<short> TLateOut { get; set; }
        public Nullable<short> TWorkTime { get; set; }
        public Nullable<double> TotalOT { get; set; }
        public Nullable<short> TotalLossWorkMin { get; set; }
        public Nullable<short> TotalExtraWorkMin { get; set; }
        public Nullable<short> ExpectedWrkTime { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<short> DesgID { get; set; }
        public string DesignationName { get; set; }
        public Nullable<short> TypID { get; set; }
        public string TypeName { get; set; }
        public Nullable<short> ShftID { get; set; }
        public string ShiftName { get; set; }
        public Nullable<short> GrdID { get; set; }
        public string GradeName { get; set; }
        public string SectionName { get; set; }
        public Nullable<short> DeptID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<short> LocID { get; set; }
        public string LocationName { get; set; }
        public string EmpNo { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string FathersName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CNICNo { get; set; }
        public string BloodGroup { get; set; }
        public string MaritalStatus { get; set; }
        public string Address { get; set; }
        public Nullable<int> EmpImage { get; set; }
        public string Country { get; set; }
        public string LandLine { get; set; }
        public string MobileNo { get; set; }
        public string EmergencyContactNo { get; set; }
        public string EmailID { get; set; }
        public string OfficialContactNo { get; set; }
        public Nullable<short> SecID { get; set; }
        public Nullable<bool> ProcessAttendance { get; set; }
        public string Status { get; set; }
        public string CardNo { get; set; }
        public Nullable<int> ReportingToID { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public string OfficialEmailID { get; set; }
        public string PinCode { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public Nullable<bool> FaceTemp { get; set; }
        public Nullable<int> FPTemp { get; set; }
        public string MonthlyStatus { get; set; }
        public Nullable<int> PRID { get; set; }
        public string PName { get; set; }
        public Nullable<System.DateTime> PStartDate { get; set; }
        public Nullable<System.DateTime> PEndDate { get; set; }
        public string PStageID { get; set; }
        public Nullable<double> TotalOTAmount { get; set; }
        public Nullable<double> TROTHour { get; set; }
        public Nullable<double> TGZOTHour { get; set; }
        public Nullable<double> TNOTHour { get; set; }
        public Nullable<double> GOTAmount { get; set; }
        public Nullable<double> ROTAmount { get; set; }
        public Nullable<double> NOTAmount { get; set; }
    }
}
