//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmpHistory
    {
        public string LocationName { get; set; }
        public string SectionName { get; set; }
        public string DesignationName { get; set; }
        public string TypeName { get; set; }
        public string ShiftName { get; set; }
        public string GradeName { get; set; }
        public int EmployeeID { get; set; }
        public string EmpNo { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string FathersName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CNICNo { get; set; }
        public string BloodGroup { get; set; }
        public string MaritalStatus { get; set; }
        public string Address { get; set; }
        public string LandLine { get; set; }
        public string MobileNo { get; set; }
        public string Country { get; set; }
        public string EmergencyContactNo { get; set; }
        public string EmailID { get; set; }
        public string OfficialContactNo { get; set; }
        public string OfficialEmailID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string CardNo { get; set; }
        public string PinCode { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public Nullable<bool> FaceTemp { get; set; }
        public Nullable<int> ReportingToID { get; set; }
        public string DepartmentName { get; set; }
        public string DomicileCity { get; set; }
        public string Address2 { get; set; }
        public string DomicileProvince { get; set; }
        public string GrdName { get; set; }
        public string ScaleName { get; set; }
        public string StartSession { get; set; }
        public string EndSession { get; set; }
        public string Specialization { get; set; }
        public string Institute { get; set; }
        public string Degree { get; set; }
        public string distinction { get; set; }
        public string Name { get; set; }
        public string Relationship { get; set; }
        public string Expr1 { get; set; }
        public string Designation { get; set; }
        public string OrganisationName { get; set; }
        public string OrgAddress { get; set; }
        public string OrgContactNumber { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string JobDescription { get; set; }
        public Nullable<double> TrainingYear { get; set; }
        public string Training { get; set; }
        public string TrainingInstitute { get; set; }
        public Nullable<System.DateTime> WarningDate { get; set; }
        public string WarningReason { get; set; }
        public string WarningFrom { get; set; }
        public Nullable<System.DateTime> AppreciationDate { get; set; }
        public string AppreciationReason { get; set; }
        public string AppreciationFrom { get; set; }
        public Nullable<short> ODesignationID { get; set; }
        public Nullable<short> OLocID { get; set; }
        public Nullable<short> OSectionID { get; set; }
        public Nullable<short> OSecID { get; set; }
        public Nullable<short> ODeptID { get; set; }
        public Nullable<short> OEmpTypeID { get; set; }
        public Nullable<short> OGradeID { get; set; }
        public string OGrd { get; set; }
        public Nullable<int> OReportingTo { get; set; }
        public string OScale { get; set; }
        public Nullable<System.DateTime> OStationJoinDate { get; set; }
        public Nullable<System.DateTime> OCurrentDate { get; set; }
        public Nullable<System.DateTime> ORetirementDate { get; set; }
        public Nullable<System.DateTime> ODateOfCommision { get; set; }
        public Nullable<System.DateTime> OGovtSrvsDate { get; set; }
        public Nullable<System.DateTime> OOrgJoinDate { get; set; }
        public Nullable<System.DateTime> OTerminationDate { get; set; }
        public Nullable<short> DeptID { get; set; }
        public Nullable<short> SectionID { get; set; }
        public Nullable<short> LocID { get; set; }
        public Nullable<short> SecID { get; set; }
        public Nullable<short> DesgID { get; set; }
        public Nullable<short> TypID { get; set; }
        public Nullable<short> ShftID { get; set; }
        public Nullable<bool> DependentDeleted { get; set; }
        public Nullable<bool> ExpDeleted { get; set; }
        public Nullable<bool> TrainingDeleted { get; set; }
        public Nullable<bool> WarningDeleted { get; set; }
        public Nullable<bool> AppreciationDeleted { get; set; }
        public Nullable<bool> QualifDeleted { get; set; }
        public Nullable<int> QualificationID { get; set; }
        public Nullable<int> DependentID { get; set; }
        public Nullable<int> ExperienceID { get; set; }
        public Nullable<int> TrainingID { get; set; }
        public Nullable<int> WarningID { get; set; }
        public Nullable<int> AppreciationID { get; set; }
        public string NewDesignation { get; set; }
        public string NewLocation { get; set; }
        public string NewSection { get; set; }
        public string NewDepartment { get; set; }
        public string NewType { get; set; }
        public string NewReportToName { get; set; }
        public string Duration { get; set; }
        public string TrainingPlace { get; set; }
        public Nullable<bool> InternationalTraining { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
    }
}
