//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewVisitorsVisit
    {
        public string VName { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public int PVisitID { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public string Remark { get; set; }
        public string OtherDetail { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string VisitorCardNo { get; set; }
        public string ReasonName { get; set; }
        public int PVisitorID { get; set; }
        public string VComapny { get; set; }
        public string CNICNo { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string VisitorType { get; set; }
        public string VDesigName { get; set; }
        public string VSectionName { get; set; }
        public string VReason { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> PSerialID { get; set; }
        public string FloorName { get; set; }
        public Nullable<int> FloorID { get; set; }
        public Nullable<int> RFCardID { get; set; }
        public string CardNo { get; set; }
        public string SerialDisplay { get; set; }
        public int VisitorID { get; set; }
        public Nullable<int> VisitTypeID { get; set; }
        public string PVisitTypeName { get; set; }
        public Nullable<bool> Schedule { get; set; }
        public Nullable<bool> IsVehicleOrPerson { get; set; }
        public Nullable<bool> VehicleAccess { get; set; }
        public Nullable<bool> IsManual { get; set; }
        public Nullable<bool> SendRemarksInMessage { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string OtherReasonRemarks { get; set; }
        public string VVCompany { get; set; }
        public Nullable<int> TotalPerson { get; set; }
    }
}
