//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDailyOTEntry
    {
        public Nullable<int> ReportingToID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmpNo { get; set; }
        public string GradeName { get; set; }
        public string DesignationName { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<short> DeptID { get; set; }
        public Nullable<short> SecID { get; set; }
        public Nullable<short> DesgID { get; set; }
        public Nullable<short> TypID { get; set; }
        public string TypeName { get; set; }
        public Nullable<short> ShftID { get; set; }
        public string ShiftName { get; set; }
        public string SectionName { get; set; }
        public Nullable<short> DepartmentID { get; set; }
        public string LocationName { get; set; }
        public Nullable<short> LocID { get; set; }
        public Nullable<short> GrdID { get; set; }
        public string FullName { get; set; }
        public int POTAID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string EmpDate { get; set; }
        public Nullable<int> ActualOTMin { get; set; }
        public Nullable<int> ApprovedOTMin { get; set; }
        public string Remarks { get; set; }
        public Nullable<double> OTAmount { get; set; }
        public string StatusID { get; set; }
        public string DutyCode { get; set; }
        public Nullable<System.TimeSpan> DutyTime { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public Nullable<short> WorkMin { get; set; }
        public Nullable<double> PDays { get; set; }
        public Nullable<double> AbDays { get; set; }
        public Nullable<double> LeaveDays { get; set; }
        public Nullable<short> LateOut { get; set; }
        public Nullable<short> EarlyIn { get; set; }
        public Nullable<short> EarlyOut { get; set; }
        public Nullable<short> LateIn { get; set; }
        public Nullable<short> NOTMin { get; set; }
        public Nullable<short> ROTMin { get; set; }
        public Nullable<short> GZOTMin { get; set; }
        public Nullable<short> BreakMin { get; set; }
        public Nullable<short> TotalShortMin { get; set; }
        public Nullable<short> SLMin { get; set; }
        public Nullable<bool> StatusP { get; set; }
        public Nullable<bool> StatusAB { get; set; }
        public Nullable<bool> StatusLI { get; set; }
        public Nullable<bool> StatusLO { get; set; }
        public Nullable<bool> StatusEI { get; set; }
        public Nullable<bool> StatusEO { get; set; }
        public Nullable<bool> StatusOT { get; set; }
        public Nullable<bool> StatusGZOT { get; set; }
        public Nullable<bool> StatusGZ { get; set; }
        public Nullable<bool> StatusROT { get; set; }
        public Nullable<bool> StatusDO { get; set; }
        public Nullable<bool> StatusSL { get; set; }
        public Nullable<bool> StatusOD { get; set; }
        public Nullable<bool> StatusHL { get; set; }
        public Nullable<bool> StatusLeave { get; set; }
        public Nullable<bool> StatusMN { get; set; }
        public Nullable<bool> StatusIN { get; set; }
        public Nullable<bool> StatusBreak { get; set; }
        public Nullable<short> ShifMin { get; set; }
        public Nullable<short> BreakMins { get; set; }
        public string AttRemarks { get; set; }
        public Nullable<System.DateTime> Tin0 { get; set; }
        public Nullable<System.DateTime> Tout0 { get; set; }
        public Nullable<System.DateTime> Tin1 { get; set; }
        public Nullable<System.DateTime> Tout1 { get; set; }
        public Nullable<System.DateTime> Tin2 { get; set; }
        public Nullable<System.DateTime> Tout2 { get; set; }
        public Nullable<System.DateTime> Tin3 { get; set; }
        public Nullable<System.DateTime> Tout3 { get; set; }
        public Nullable<System.DateTime> Tin4 { get; set; }
        public Nullable<System.DateTime> Tout4 { get; set; }
        public Nullable<System.DateTime> OTDate { get; set; }
        public string OTEntryDutyCode { get; set; }
        public Nullable<int> ForwardToID { get; set; }
        public Nullable<int> SupervisorID { get; set; }
        public Nullable<int> ApprovedByID { get; set; }
        public Nullable<System.DateTime> PtoFCDateTime { get; set; }
        public Nullable<System.DateTime> FtoARDateTime { get; set; }
        public Nullable<int> FtoARUserID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<int> OTProcessingPeriodID { get; set; }
        public Nullable<int> UCUserID { get; set; }
        public string UCUserName { get; set; }
        public string UCFullName { get; set; }
        public string UCDesignationName { get; set; }
        public string UCODName { get; set; }
        public Nullable<int> UCEmpID { get; set; }
        public Nullable<int> UFEmpID { get; set; }
        public string UFFullName { get; set; }
        public string UFDesignationName { get; set; }
        public string UFODName { get; set; }
        public Nullable<int> UFUserID { get; set; }
        public string UFUserName { get; set; }
        public Nullable<int> USUserID { get; set; }
        public Nullable<int> USEmpID { get; set; }
        public string USFullName { get; set; }
        public string USDesignationName { get; set; }
        public string USODName { get; set; }
        public string USUserName { get; set; }
        public Nullable<int> URUserID { get; set; }
        public string URUserName { get; set; }
        public Nullable<int> UREmpID { get; set; }
        public string URFullName { get; set; }
        public string URDesignationName { get; set; }
        public string URODName { get; set; }
        public Nullable<int> UAUserID { get; set; }
        public string UAUserName { get; set; }
        public Nullable<int> UAEmpID { get; set; }
        public string UAFullName { get; set; }
        public string UADesignationName { get; set; }
        public string UAODName { get; set; }
        public Nullable<int> UPFUserID { get; set; }
        public string UPFUserName { get; set; }
        public string UPFFullName { get; set; }
        public string UPFDesignationName { get; set; }
        public string UPFODName { get; set; }
        public Nullable<int> UFFUserID { get; set; }
        public string UFFUserName { get; set; }
        public string UFFFullName { get; set; }
        public string UFFDesignationName { get; set; }
        public string UFFODName { get; set; }
        public string UFUserType { get; set; }
        public Nullable<double> NormalOTAmount { get; set; }
        public Nullable<double> RestOTAmount { get; set; }
        public Nullable<double> GZOTAmount { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public Nullable<double> TaxAmount { get; set; }
        public string BankAccount { get; set; }
    }
}
