//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMS_VisitorInfo
    {
        public VMS_VisitorInfo()
        {
            this.VMS_VisitInfo = new HashSet<VMS_VisitInfo>();
        }
    
        public int PVisitorID { get; set; }
        public string VName { get; set; }
        public string VComapny { get; set; }
        public string CNICNo { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string VisitorType { get; set; }
        public string VDesigName { get; set; }
        public string VSectionName { get; set; }
        public string VReason { get; set; }
    
        public virtual ICollection<VMS_VisitInfo> VMS_VisitInfo { get; set; }
    }
}
