//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMS_Floor
    {
        public VMS_Floor()
        {
            this.Att_RFIDCard = new HashSet<Att_RFIDCard>();
            this.VMS_VisitInfo = new HashSet<VMS_VisitInfo>();
        }
    
        public int PFloorID { get; set; }
        public string FloorName { get; set; }
    
        public virtual ICollection<Att_RFIDCard> Att_RFIDCard { get; set; }
        public virtual ICollection<VMS_VisitInfo> VMS_VisitInfo { get; set; }
    }
}
