//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMS_SMSSend
    {
        public int PSID { get; set; }
        public Nullable<int> VisitID { get; set; }
        public string MessageSendNo { get; set; }
        public Nullable<System.DateTime> SendDateTime { get; set; }
    }
}
