//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMS_VisitDevice
    {
        public int VDPID { get; set; }
        public Nullable<int> VisitID { get; set; }
        public Nullable<int> VisitorID { get; set; }
        public Nullable<short> ReaderID { get; set; }
        public string Remarks { get; set; }
    }
}
