//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTAWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMS_VisitInfo
    {
        public int PVisitID { get; set; }
        public int VisitorID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public Nullable<int> RFCardID { get; set; }
        public Nullable<int> FloorID { get; set; }
        public string Remark { get; set; }
        public Nullable<int> VisitTypeID { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public string OtherDetail { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string VisitorCardNo { get; set; }
        public Nullable<bool> Schedule { get; set; }
        public Nullable<bool> IsVehicleOrPerson { get; set; }
        public Nullable<bool> VehicleAccess { get; set; }
        public string OtherReasonRemarks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> SendRemarksInMessage { get; set; }
        public Nullable<bool> IsManual { get; set; }
        public string VVCompany { get; set; }
        public Nullable<int> TotalPerson { get; set; }
    
        public virtual Att_RFIDCard Att_RFIDCard { get; set; }
        public virtual HR_Employee HR_Employee { get; set; }
        public virtual VMS_Floor VMS_Floor { get; set; }
        public virtual VMS_VisitorInfo VMS_VisitorInfo { get; set; }
    }
}
